version: "3.3"

services:

  caddy:
    image: "caddy:2-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"

  core-app:
    build: ./dotnetapp

volumes: 
  caddy_data:
  caddy_config: